apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-serving-cert
  namespace: cacppt-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  dnsNames:
  - cacppt-webhook-service.cacppt-system.svc
  - cacppt-webhook-service.cacppt-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cacppt-selfsigned-issuer
  secretName: cacppt-webhook-service-cert
