apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    control-plane: controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-controller-manager
  namespace: cacppt-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: control-plane-talos
      control-plane: controller-manager
      clusterctl.cluster.x-k8s.io: ""
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: control-plane-talos
        control-plane: controller-manager
        clusterctl.cluster.x-k8s.io: ""
    spec:
      containers:
      - args:
        - --metrics-bind-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: ghcr.io/talos-systems/cluster-api-control-plane-talos-controller:v0.3.1
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: cacppt-webhook-service-cert
