apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-selfsigned-issuer
  namespace: cacppt-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  selfSigned: {}
