apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
  name: caps-serving-cert
  namespace: capi-webhook-system # kpt-set: ${capi-webhook-system-namespace}
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  dnsNames:
  - caps-webhook-service.capi-webhook-system.svc # kpt-set: caps-webhook-service.${capi-webhook-system-namespace}.svc
  - caps-webhook-service.capi-webhook-system.svc.cluster.local # kpt-set: caps-webhook-service.${capi-webhook-system-namespace}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: caps-selfsigned-issuer
  secretName: caps-webhook-service-cert
