apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
  name: caps-serving-cert
  namespace: capi-webhook-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  dnsNames:
  - caps-webhook-service.capi-webhook-system.svc
  - caps-webhook-service.capi-webhook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: caps-selfsigned-issuer
  secretName: caps-webhook-service-cert
