apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
  name: caps-selfsigned-issuer
  namespace: capi-webhook-system # kpt-set: ${capi-webhook-system-namespace}
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  selfSigned: {}
