apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
  name: caps-webhook-service
  namespace: capi-webhook-system # kpt-set: ${capi-webhook-system-namespace}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
