apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
  name: caps-webhook-service
  namespace: capi-webhook-system
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
