apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: cluster-name-control-plane
  labels:
    role: control-plane
    metalmachinetemplate: cluster-name-control-plane
    cluster: cluster-name
  namespace: default
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v0.14
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: cluster-name-control-plane
  replicas: 1
  version: v1.20.15
