apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-metalcluster-from-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: MetalCluster
    targets:
      - select:
          kind: Cluster
        fieldPaths:
          - spec.infrastructureRef.name
        options:
          create: true
