apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-taloscontrolplane-from-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: TalosControlPlane
    targets:
      - select:
          kind: Cluster
        fieldPaths:
          - spec.controlPlaneRef.name
        options:
          create: true
