apiVersion: v1
kind: Service
metadata: # kpt-merge: capi-webhook-system/cacppt-webhook-service
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
  name: cacppt-webhook-service
  namespace: capi-webhook-system
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    cluster.x-k8s.io/provider: control-plane-talos
    control-plane: controller-manager
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
