apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
  name: capd-serving-cert
  namespace: capd-system # kpt-set: ${capi-provider-namespace}
spec:
  dnsNames:
  - capd-webhook-service.capd-system.svc # kpt-set: capd-webhook-service.${capi-provider-namespace}.svc
  - capd-webhook-service.capd-system.svc.cluster.local # kpt-set: capd-webhook-service.${capi-provider-namespace}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capd-selfsigned-issuer
  secretName: capd-webhook-service-cert
