apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
  name: capd-serving-cert
  namespace: capd-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  dnsNames:
  - capd-webhook-service.capd-system.svc
  - capd-webhook-service.capd-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capd-selfsigned-issuer
  secretName: capd-webhook-service-cert
