apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
  name: capd-selfsigned-issuer
  namespace: capd-system # kpt-set: ${capi-provider-namespace}
spec:
  selfSigned: {}
