apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-environment-from-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: Environment
    targets:
      - select:
          kind: Server
        fieldPaths:
          - spec.environmentRef.name
        options:
          create: true
      - select:
          kind: ServerClass
        fieldPaths:
          - spec.environmentRef.name
        options:
          create: true
