apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
  name: capi-webhook-service
  namespace: capi-webhook-system # kpt-set: ${capi-webhook-system-namespace}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
    protocol: TCP
  selector:
    cluster.x-k8s.io/provider: cluster-api
