apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ""
  name: capi-kubeadm-control-plane-system-capi-kubeadm-control-plane-proxy-rolebinding # kpt-set: ${capi-provider-namespace}-capi-kubeadm-control-plane-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capi-kubeadm-control-plane-system-capi-kubeadm-control-plane-proxy-role # kpt-set: ${capi-provider-namespace}-capi-kubeadm-control-plane-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capi-kubeadm-control-plane-system # kpt-set: ${capi-provider-namespace}
