apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata: # kpt-merge: /ensureportprotocolsareset
  name: ensureportprotocolsareset
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
spec:
  crd:
    spec:
      names:
        kind: ensurePortProtocolsAreSet
        validation:
          openAPIV3Schema:
            properties:
              keys:
                type: array
                items:
                  type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |-
        package ensureportprotocolsareset

        missing(obj, field) = true {
          not obj[field]
        }

        violation[{"msg": msg, "details": {}}] {
          port := input.review.object.spec.ports[_]
          missing(port, "protocol")
          msg := sprintf("port <%v> has no protocol set", [port.port])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ensurePortProtocolsAreSet
metadata: # kpt-merge: /ensureportprotocolsareset
  name: ensureportprotocolsareset
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
spec:
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Service
