apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ""
  name: capi-kubeadm-control-plane-leader-election-rolebinding
  namespace: capi-kubeadm-control-plane-system # kpt-set: ${capi-provider-namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capi-kubeadm-control-plane-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capi-kubeadm-control-plane-system # kpt-set: ${capi-provider-namespace}
