apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    control-plane: caps-controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: caps-controller-manager
  namespace: sidero-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: infrastructure-sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      cluster.x-k8s.io/v1alpha4: v1alpha3
      cluster.x-k8s.io/v1beta1: v1alpha3
      control-plane: caps-controller-manager
      clusterctl.cluster.x-k8s.io: ""
  template:
    metadata:
      labels:
        app: sidero
        cluster.x-k8s.io/provider: infrastructure-sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        cluster.x-k8s.io/v1alpha4: v1alpha3
        cluster.x-k8s.io/v1beta1: v1alpha3
        control-plane: caps-controller-manager
        clusterctl.cluster.x-k8s.io: ""
      annotations:
        config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
    spec:
      containers:
      - args:
        - --metrics-bind-addr=127.0.0.1:8080
        command:
        - /manager
        image: ghcr.io/talos-systems/caps-controller-manager:v0.5.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: caps-webhook-service-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    control-plane: sidero-controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-controller-manager
  namespace: sidero-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: infrastructure-sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      cluster.x-k8s.io/v1alpha4: v1alpha3
      cluster.x-k8s.io/v1beta1: v1alpha3
      control-plane: sidero-controller-manager
      clusterctl.cluster.x-k8s.io: ""
  template:
    metadata:
      labels:
        app: sidero
        cluster.x-k8s.io/provider: infrastructure-sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        cluster.x-k8s.io/v1alpha4: v1alpha3
        cluster.x-k8s.io/v1beta1: v1alpha3
        control-plane: sidero-controller-manager
        clusterctl.cluster.x-k8s.io: ""
      annotations:
        config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
    spec:
      containers:
      - args:
        - --metrics-bind-addr=127.0.0.1:8080
        - --api-endpoint=-
        - --api-port=8081
        - --http-port=8081
        - --extra-agent-kernel-args=-
        - --boot-from-disk-method=ipxe-exit
        - --auto-accept-servers=false
        - --insecure-wipe=true
        - --auto-bmc-setup=true
        - --server-reboot-timeout=20m
        - --ipmi-pxe-method=uefi
        - --test-power-simulated-explicit-failure-prob=0
        - --test-power-simulated-silent-failure-prob=0
        command:
        - /manager
        env:
        - name: API_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: ghcr.io/talos-systems/sidero-controller-manager:v0.5.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 69
          name: tftp
          protocol: UDP
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - args:
        - --wireguard-endpoint=-
        - --wireguard-port=51821
        command:
        - /siderolink-manager
        env:
        - name: API_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: ghcr.io/talos-systems/sidero-controller-manager:v0.5.0
        imagePullPolicy: Always
        name: siderolink
        ports:
        - containerPort: 51821
          name: siderolink
          protocol: UDP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
        volumeMounts:
        - mountPath: /dev/net/tun
          name: dev-tun
      - command:
        - /log-receiver
        image: ghcr.io/talos-systems/sidero-controller-manager:v0.5.0
        imagePullPolicy: Always
        name: serverlogs
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      - command:
        - /events-manager
        image: ghcr.io/talos-systems/sidero-controller-manager:v0.5.0
        imagePullPolicy: Always
        name: serverevents
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      hostNetwork: false
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-tun
