apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-metalmachinetemplate-from-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: MetalMachineTemplate
    targets:
      - select:
          kind: TalosControlPlane
        fieldPaths:
          - spec.infrastructureTemplate.name
        options:
          create: true
      - select:
          kind: MachineDeployment
        fieldPaths:
          - spec.template.spec.infrastructureRef.name
        options:
          create: true
