apiVersion: v1
kind: Namespace
metadata:
  labels:
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
    control-plane: controller-manager
  name: capi-webhook-system # kpt-set: ${capi-webhook-system-namespace}
