apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-metalmachinetemplate-from-name-workers
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    role: workers
replacements:
  - source:
      kind: MetalMachineTemplate
    targets:
      - select:
          kind: TalosControlPlane
        fieldPaths:
          - spec.infrastructureTemplate.name
        options:
          create: true
      - select:
          kind: MachineDeployment
        fieldPaths:
          - spec.template.spec.infrastructureRef.name
        options:
          create: true
      - select:
          group: bootstrap.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.metalmachinetemplate
        options:
          create: true
      - select:
          group: cluster.x-k8s.io
        fieldPaths:
          - metadata.labels.metalmachinetemplate
        options:
          create: true
      - select:
          group: controlplane.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.metalmachinetemplate
        options:
          create: true
      - select:
          group: infrastructure.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.metalmachinetemplate
        options:
          create: true
      - select:
          group: metal.sidero.dev
          version: v1alpha1
        fieldPaths:
          - metadata.labels.metalmachinetemplate
        options:
          create: true
