apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
  name: cacppt-selfsigned-issuer
  namespace: capi-webhook-system # kpt-set: ${capi-webhook-system-namespace}
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  selfSigned: {}
