apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
  name: cacppt-webhook-service
  namespace: capi-webhook-system # kpt-set: ${capi-webhook-system-namespace}
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    cluster.x-k8s.io/provider: controlplane-talos
    control-plane: controller-manager
