apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata: # kpt-merge: capi-webhook-system/cacppt-serving-cert
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
  name: cacppt-serving-cert
  namespace: capi-webhook-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  dnsNames:
  - cacppt-webhook-service.capi-webhook-system.svc
  - cacppt-webhook-service.capi-webhook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cacppt-selfsigned-issuer
  secretName: cacppt-webhook-service-cert
