apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
  name: capd-webhook-service
  namespace: capd-system
spec:
  ports:
  - port: 443
    targetPort: webhook-server
    protocol: TCP
  selector:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
