apiVersion: v1
kind: Service
metadata: # kpt-merge: cacppt-system/cacppt-controller-manager-metrics-service
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    control-plane: controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-controller-manager-metrics-service
  namespace: cacppt-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    cluster.x-k8s.io/provider: control-plane-talos
    control-plane: controller-manager
    clusterctl.cluster.x-k8s.io: ""
