apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: caps-serving-cert
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
spec:
  dnsNames:
  - caps-webhook-service.sidero-system.svc # kpt-set: caps-webhook-service.${capi-provider-namespace}.svc
  - caps-webhook-service.sidero-system.svc.cluster.local # kpt-set: caps-webhook-service.${capi-provider-namespace}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: caps-selfsigned-issuer
  secretName: caps-webhook-service-cert
