apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-metadata-server
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      control-plane: metal-metadata-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sidero
        cluster.x-k8s.io/provider: sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        control-plane: metal-metadata-server
    spec:
      containers:
      - args:
        - --port=8080 # kpt-set: --port=${port}
        image: ghcr.io/talos-systems/metal-metadata-server:v0.3.0-alpha.0
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
status: {}
