apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
    control-plane: metal-controller-manager
  name: sidero-controller-manager
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      control-plane: metal-controller-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sidero
        cluster.x-k8s.io/provider: sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        control-plane: metal-controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443 # kpt-set: --secure-listen-address=${secure-listen-address}
        - --upstream=http://127.0.0.1:8080/ # kpt-set: --upstream=${upstream}
        - --logtostderr=true # kpt-set: --logtostderr=${logtostderr}
        - --v=10 # kpt-set: --v=${v}
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources: {}
      - args:
        - --metrics-addr=127.0.0.1:8080 # kpt-set: --metrics-addr=${metrics-addr}
        - --api-endpoint=- # kpt-set: --api-endpoint=${api-endpoint}
        - --extra-agent-kernel-args=- # kpt-set: --extra-agent-kernel-args=${extra-agent-kernel-args}
        - --auto-accept-servers=false # kpt-set: --auto-accept-servers=${auto-accept-servers}
        - --insecure-wipe=true # kpt-set: --insecure-wipe=${insecure-wipe}
        - --auto-bmc-setup=true # kpt-set: --auto-bmc-setup=${auto-bmc-setup}
        - --server-reboot-timeout=20m # kpt-set: --server-reboot-timeout=${server-reboot-timeout}
        - --test-power-simulated-explicit-failure-prob=0 # kpt-set: --test-power-simulated-explicit-failure-prob=${test-power-simulated-explicit-failure-prob}
        - --test-power-simulated-silent-failure-prob=0 # kpt-set: --test-power-simulated-silent-failure-prob=${test-power-simulated-silent-failure-prob}
        command:
        - /manager
        env:
        - name: API_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: ghcr.io/talos-systems/metal-controller-manager:v0.3.0-alpha.0
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 69
          name: tftp
          protocol: UDP
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 50100
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
status: {}
