apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: sidero-controller-manager
  name: sidero-controller-manager
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      control-plane: sidero-controller-manager
  template:
    metadata:
      labels:
        app: sidero
        cluster.x-k8s.io/provider: sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        control-plane: sidero-controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080 # kpt-set: --metrics-addr=${metrics-addr}
        - --api-endpoint=- # kpt-set: --api-endpoint=${api-endpoint}
        - --api-port=8081 # kpt-set: --api-port=${api-port}
        - --extra-agent-kernel-args=- # kpt-set: --extra-agent-kernel-args=${extra-agent-kernel-args}
        - --boot-from-disk-method=ipxe-exit # kpt-set: --boot-from-disk-method=${boot-from-disk-method}
        - --auto-accept-servers=false # kpt-set: --auto-accept-servers=${auto-accept-servers}
        - --insecure-wipe=true # kpt-set: --insecure-wipe=${insecure-wipe}
        - --auto-bmc-setup=true # kpt-set: --auto-bmc-setup=${auto-bmc-setup}
        - --server-reboot-timeout=20m # kpt-set: --server-reboot-timeout=${server-reboot-timeout}
        - --test-power-simulated-explicit-failure-prob=0 # kpt-set: --test-power-simulated-explicit-failure-prob=${test-power-simulated-explicit-failure-prob}
        - --test-power-simulated-silent-failure-prob=0 # kpt-set: --test-power-simulated-silent-failure-prob=${test-power-simulated-silent-failure-prob}
        command:
        - /manager
        env:
        - name: API_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: ghcr.io/talos-systems/sidero-controller-manager:v0.3.3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
        name: manager
        ports:
        - containerPort: 69
          name: tftp
          protocol: UDP
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      hostNetwork: false
      terminationGracePeriodSeconds: 10
