apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: caps-controller-manager
  namespace: sidero-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: infrastructure-sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      control-plane: caps-controller-manager
      clusterctl.cluster.x-k8s.io: ""
  template:
    metadata:
      labels:
        app: sidero
        cluster.x-k8s.io/provider: infrastructure-sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        control-plane: caps-controller-manager
        clusterctl.cluster.x-k8s.io: ""
      annotations:
        config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
    spec:
      containers:
      - command:
        - /manager
        image: ghcr.io/talos-systems/caps-controller-manager:v0.3.3
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: sidero-controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-controller-manager
  namespace: sidero-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: infrastructure-sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      control-plane: sidero-controller-manager
      clusterctl.cluster.x-k8s.io: ""
  template:
    metadata:
      labels:
        app: sidero
        cluster.x-k8s.io/provider: infrastructure-sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        control-plane: sidero-controller-manager
        clusterctl.cluster.x-k8s.io: ""
      annotations:
        config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --api-endpoint=-
        - --api-port=8081
        - --extra-agent-kernel-args=-
        - --boot-from-disk-method=ipxe-exit
        - --auto-accept-servers=false
        - --insecure-wipe=true
        - --auto-bmc-setup=true
        - --server-reboot-timeout=20m
        - --test-power-simulated-explicit-failure-prob=0
        - --test-power-simulated-silent-failure-prob=0
        command:
        - /manager
        env:
        - name: API_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: ghcr.io/talos-systems/sidero-controller-manager:v0.3.3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
        name: manager
        ports:
        - containerPort: 69
          name: tftp
          protocol: UDP
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      hostNetwork: false
      terminationGracePeriodSeconds: 10
