apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: caps-selfsigned-issuer
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  selfSigned: {}
