apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-controller-manager-metrics-service
  namespace: sidero-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
    protocol: TCP
  selector:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
    clusterctl.cluster.x-k8s.io: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-tftp
  namespace: sidero-system
spec:
  ports:
  - port: 69
    protocol: UDP
    targetPort: tftp
  selector:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: sidero-controller-manager
    clusterctl.cluster.x-k8s.io: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-http
  namespace: sidero-system
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: sidero-controller-manager
    clusterctl.cluster.x-k8s.io: ""
