apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
  name: sidero-controller-manager-metrics-service
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
