apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
  name: sidero-http
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: sidero-controller-manager
