apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-tftp
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
spec:
  ports:
  - port: 69
    protocol: UDP
    targetPort: tftp
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: metal-controller-manager
