apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-cluster-from-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: Cluster
      fieldPath: metadata.namespace
    targets:
      - select:
          group: bootstrap.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.namespace
        options:
          create: true

      - select:
          group: cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.namespace
        options:
          create: true

      - select:
          group: controlplane.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.namespace
        options:
          create: true

      - select:
          group: infrastructure.cluster.x-k8s.io
          version: v1alpha3
        reject:
          - kind: ServerBinding
        fieldPaths:
          - metadata.namespace
        options:
          create: true

  - source:
      kind: Cluster
    targets:
      - select:
          kind: MachineDeployment
        fieldPaths:
          - spec.clusterName
          - spec.template.spec.clusterName
        options:
          create: true

      - select:
          kind: ServerClass
        fieldPaths:
          - spec.selector.matchLabels.cluster
        options:
          create: true

      - select:
          group: bootstrap.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.cluster
        options:
          create: true

      - select:
          group: cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.cluster
        options:
          create: true

      - select:
          group: controlplane.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.cluster
        options:
          create: true

      - select:
          group: infrastructure.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.cluster
        options:
          create: true

      - select:
          group: metal.sidero.dev
          version: v1alpha1
        fieldPaths:
          - metadata.labels.cluster
        options:
          create: true
