apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    control-plane: controller-manager
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-controller-manager
  namespace: cacppt-system
  annotations:
    config.kubernetes.io/depends-on: apps/namespaces/cert-manager/Deployment/cert-manager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: controlplane-talos
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: controlplane-talos
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: ghcr.io/talos-systems/cluster-api-control-plane-talos-controller:v0.2.0
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
