apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  name: cacppt-controller-manager
  namespace: cacppt-system # kpt-set: ${capi-provider-namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: controlplane-talos
      control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster.x-k8s.io/provider: controlplane-talos
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080 # kpt-set: --metrics-addr=${metrics-addr}
        - --enable-leader-election=true # kpt-set: --enable-leader-election=${enable-leader-election}
        command:
        - /manager
        image: ghcr.io/talos-systems/cluster-api-control-plane-talos-controller:v0.2.0
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
status: {}
