apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    cluster.x-k8s.io/provider: controlplane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-manager-role
  namespace: cacppt-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - rbac
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - rbac
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - watch
