apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  name: cacppt-controller-manager-metrics-service
  namespace: cacppt-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
    protocol: TCP
  selector:
    cluster.x-k8s.io/provider: controlplane-talos
    control-plane: controller-manager
