apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-serverclass-from-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: ServerClass
    targets:
      - select:
          kind: MetalMachineTemplate
        fieldPaths:
          - spec.template.spec.serverClassRef.name
        options:
          create: true
