apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/provider: controlplane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
