apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-system-cacppt-manager-rolebinding # kpt-set: ${capi-provider-namespace}-cacppt-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cacppt-system-cacppt-manager-role # kpt-set: ${capi-provider-namespace}-cacppt-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cacppt-system # kpt-set: ${capi-provider-namespace}
