apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: set-environment-from-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
  - source:
      kind: Environment
    targets:
      - select:
          kind: ServerClass
        fieldPaths:
          - spec.environmentRef.name
        options:
          create: true
      - select:
          kind: Server
        fieldPaths:
          - spec.environmentRef.name
        options:
          create: true
      - select:
          kind: ServerClass
        fieldPaths:
          - spec.selector.matchLabels.environment
        options:
          create: true
      - select:
          group: bootstrap.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.environment
        options:
          create: true
      - select:
          group: cluster.x-k8s.io
        fieldPaths:
          - metadata.labels.environment
        options:
          create: true
      - select:
          group: controlplane.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.environment
        options:
          create: true
      - select:
          group: infrastructure.cluster.x-k8s.io
          version: v1alpha3
        fieldPaths:
          - metadata.labels.environment
        options:
          create: true
      - select:
          group: metal.sidero.dev
          version: v1alpha1
        fieldPaths:
          - metadata.labels.environment
        options:
          create: true
