apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
  name: capd-system-capd-proxy-rolebinding # kpt-set: ${capi-provider-namespace}-capd-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capd-system-capd-proxy-role # kpt-set: ${capi-provider-namespace}-capd-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capd-system # kpt-set: ${capi-provider-namespace}
