apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  name: capd-system # kpt-set: ${capi-provider-namespace}
