apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
  name: sidero-server-editor-role
rules:
- apiGroups:
  - metal.sidero.dev
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.sidero.dev
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
