apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-system-sidero-metadata-server-role # kpt-set: ${capi-provider-namespace}-sidero-metadata-server-role
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - get
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalmachines
  verbs:
  - list
- apiGroups:
  - metal.sidero.dev
  resources:
  - servers
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
