apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-system-sidero-proxy-rolebinding # kpt-set: ${capi-provider-namespace}-sidero-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidero-system-sidero-proxy-role # kpt-set: ${capi-provider-namespace}-sidero-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: sidero-system # kpt-set: ${capi-provider-namespace}
