apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: sidero-cluster-workers # kpt-set: ${workers-serverclass}
  namespace: default
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: sidero-cluster-workers # kpt-set: ${workers-serverclass}
