apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: clustername-workers # kpt-set: ${workers-name}
  namespace: default
spec:
  template:
    spec:
      generateType: join
      talosVersion: v0.14 # kpt-set: ${talos-version}
